color:
  saturation: 0.2701396
  brandStrength: 0.9196864
  rhythmicContrast: 1
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  lightness: 0.2024704
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.7556391
typography_spectrum: 0.3861439
name: JoeBar
